version: '2'
services:
  docs:
    build: ./
    volumes:
      - '.:/docs'
      - npm-app:/docs/node_modules
    ports:
      - '8080:8080'
    command: bash -c 'yarn start'

volumes:
  npm-app:
    driver: local
